-- MySQL Script generated by MySQL Workbench
-- 2017년 02월 01일 (수) 오후 07시 50분 03초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Jungsan_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Jungsan_DB` ;

-- -----------------------------------------------------
-- Schema Jungsan_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Jungsan_DB` DEFAULT CHARACTER SET utf8 ;
USE `Jungsan_DB` ;

-- -----------------------------------------------------
-- Table `Jungsan_DB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jungsan_DB`.`user` ;

CREATE TABLE IF NOT EXISTS `Jungsan_DB`.`user` (
  `idx` INT(11) NOT NULL AUTO_INCREMENT,
  `userid` VARCHAR(16) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `userid_UNIQUE` (`userid` ASC));


-- -----------------------------------------------------
-- Table `Jungsan_DB`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jungsan_DB`.`group` ;

CREATE TABLE IF NOT EXISTS `Jungsan_DB`.`group` (
  `idx` INT(11) NOT NULL AUTO_INCREMENT,
  `groupname` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE INDEX `groupname_UNIQUE` (`groupname` ASC))
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Jungsan_DB`.`groupmember`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jungsan_DB`.`groupmember` ;

CREATE TABLE IF NOT EXISTS `Jungsan_DB`.`groupmember` (
  `user_idx` INT(11) NOT NULL,
  `group_idx` INT(11) NOT NULL,
  PRIMARY KEY (`user_idx`, `group_idx`),
  INDEX `fk_user_has_group_group1_idx` (`group_idx` ASC),
  INDEX `fk_user_has_group_user_idx` (`user_idx` ASC),
  CONSTRAINT `fk_user_has_group_user`
    FOREIGN KEY (`user_idx`)
    REFERENCES `Jungsan_DB`.`user` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_group_group1`
    FOREIGN KEY (`group_idx`)
    REFERENCES `Jungsan_DB`.`group` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Jungsan_DB`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jungsan_DB`.`event` ;

CREATE TABLE IF NOT EXISTS `Jungsan_DB`.`event` (
  `idx` INT(11) NOT NULL AUTO_INCREMENT,
  `group_idx` INT(11) NOT NULL,
  `date` VARCHAR(16) NOT NULL,
  `recipient_idx` INT(11) NOT NULL,
  `eventname` VARCHAR(16) NOT NULL,
  `totalcost` INT(11) NOT NULL,
  PRIMARY KEY (`idx`, `group_idx`, `recipient_idx`),
  UNIQUE INDEX `userid_UNIQUE` (`date` ASC),
  INDEX `fk_event_group1_idx` (`group_idx` ASC),
  INDEX `fk_event_user1_idx` (`recipient_idx` ASC),
  CONSTRAINT `fk_event_group1`
    FOREIGN KEY (`group_idx`)
    REFERENCES `Jungsan_DB`.`group` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_user1`
    FOREIGN KEY (`recipient_idx`)
    REFERENCES `Jungsan_DB`.`user` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Jungsan_DB`.`user_has_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jungsan_DB`.`user_has_event` ;

CREATE TABLE IF NOT EXISTS `Jungsan_DB`.`user_has_event` (
  `user_idx` INT(11) NOT NULL,
  `event_idx` INT(11) NOT NULL,
  `event_group_idx` INT(11) NOT NULL,
  `event_recipient_idx` INT(11) NOT NULL,
  `cost` INT(11) NOT NULL,
  `ispaid` TINYINT(1) NOT NULL,
  PRIMARY KEY (`user_idx`, `event_idx`, `event_group_idx`, `event_recipient_idx`),
  INDEX `fk_user_has_event_event1_idx` (`event_idx` ASC, `event_group_idx` ASC, `event_recipient_idx` ASC),
  INDEX `fk_user_has_event_user1_idx` (`user_idx` ASC),
  CONSTRAINT `fk_user_has_event_user1`
    FOREIGN KEY (`user_idx`)
    REFERENCES `Jungsan_DB`.`user` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_event_event1`
    FOREIGN KEY (`event_idx` , `event_group_idx` , `event_recipient_idx`)
    REFERENCES `Jungsan_DB`.`event` (`idx` , `group_idx` , `recipient_idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Jungsan_DB`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jungsan_DB`.`account` ;

CREATE TABLE IF NOT EXISTS `Jungsan_DB`.`account` (
  `user_idx` INT(11) NOT NULL,
  `accountnumber` VARCHAR(64) NOT NULL,
  `bank` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`user_idx`, `accountnumber`),
  INDEX `fk_account_user1_idx` (`user_idx` ASC),
  CONSTRAINT `fk_account_user1`
    FOREIGN KEY (`user_idx`)
    REFERENCES `Jungsan_DB`.`user` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
